version: '3'
services:
  postgres:
    image: postgres:9.5.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - POSTGRES_USER=postgres
      - RAILS_ENV=ci_test
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres